name: Deploy


on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: 1c20f5f3-e357-43da-a30d-397efd797b3a
          heroku_app_name: mmeng-react
          heroku_email: azaelsoares@gmail.com